services:
  scheduler:
    build: .
    image: wrs-scheduler:latest
    container_name: wrs-scheduler
    restart: unless-stopped
    ports:
      - "4000:4000"
    volumes:
      - ./data:/app/server/data
